create table cosmos.million_hearts_csv_demo (
	patient_id 		 string,
	dob	 			 string,
	dod	 			 string,
	sex	 			 string,
	race	 		 string,
	ethnicity		 string,
	non_english		 string,
	ag_worker 		 string,
	homelessness	 string,
	veteran	 		 string,
	pub_housing	 	 string,
	fpl	 			 string,
	healthinsstatus	 string,
	healthinssource	 string,
	healthcenter	 string,
	hcsite	 		 string,
	hcstate	 		 string,
	comorbid	 	 string,
	diabetes	 	 string,
	lipid	 		 string,
	disc	 		 string,
	osteo	 		 string,
	chf	 			 string,
	atrial	 		 string,
	copd	 		 string,
	kidney	 		 string,
	metabolic	 	 string,
	tobacco	 		 string,
	alcohol	 		 string,
	obesity	 		 string,
	asthma	 		 string,
	depression	 	 string,
	hiv	 			 string,
	htn	 			 string,
	clinascvd		 string,
	lcl_190	 		 string,
	lcl_190_value	 string,
	lcl_190_date	 string,
	lcl_c_base	 	 string,
	lcl_c_basedate	 string,
	hdl_base	 	 string,
	hdl_basedate	 string,
	trig_base	 	 string,
	trig_basedate	 string,
	totchol_base	 string,
	totchol_basedate string,
	activemed	 	 string,
	intol_excl	 	 string,
	intoldate	 	 string,
	other_excl 		 string
)
using csv
options (
  header = "true",
  inferSchema = "false",
  delimiter = ",",
  path = "/FileStore/tables/prod/project/million-hearts/million-hearts-csv/csv/demo"
);


